// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";
import * as CardStyles$RescriptOffline from "./CardStyles.bs.js";
import * as RecipeList$RescriptOffline from "./RecipeList.bs.js";

function AllTags(Props) {
  var tags = Props.tags;
  var recipes = Props.recipes;
  var tagComponents = Belt_Array.map(Belt_MapString.toArray(tags), (function (param) {
          var tag = param[0];
          return React.createElement("div", {
                      key: tag
                    }, React.createElement("h2", undefined, tag), React.createElement(RecipeList$RescriptOffline.make, {
                          recipeIds: param[1],
                          recipes: recipes
                        }));
        }));
  return React.createElement("div", {
              className: CardStyles$RescriptOffline.card
            }, tagComponents);
}

var make = AllTags;

export {
  make ,
  
}
/* react Not a pure module */
