// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rxdb from "rxdb";
import SchemaJson from "./Schema.json";
import PouchdbAdapterIdb from "pouchdb-adapter-idb";

var schema = SchemaJson;


Rxdb.addRxPlugin(PouchdbAdapterIdb);

function make(param) {
  return Rxdb.createRxDatabase({
                name: "recipes",
                adapter: "idb"
              }).then(function (db) {
              console.log("Loaded database", db);
              return Promise.resolve(db);
            });
}

export {
  schema ,
  make ,
  
}
/* schema Not a pure module */
