// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rxdb from "rxdb";
import SchemaJson from "./Schema.json";
import PouchdbAdapterIdb from "pouchdb-adapter-idb";

var schema = SchemaJson;

var RxDocument = {};

var RxQuery = {};

var RxCollection = {};

Rxdb.addRxPlugin(PouchdbAdapterIdb);

function make(param) {
  return Rxdb.createRxDatabase({
                name: "recipes",
                adapter: "idb"
              }).then(function (db) {
              var options = {};
              options["recipes"] = {
                schema: schema.recipes
              };
              options["tags"] = {
                schema: schema.tags
              };
              return db.addCollections(options).then(function (param) {
                          return Promise.resolve(db);
                        });
            });
}

function find(collection) {
  return collection.find();
}

function exec(query) {
  return query.exec();
}

export {
  schema ,
  RxDocument ,
  RxQuery ,
  RxCollection ,
  make ,
  find ,
  exec ,
  
}
/* schema Not a pure module */
