// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function RecipeList(Props) {
  var recipeIds = Props.recipeIds;
  var recipes = Props.recipes;
  return React.createElement("div", undefined, Belt_Array.map(Belt_Array.keep(Belt_Array.map(recipeIds, (function (recipeId) {
                            return Belt_Option.map(Belt_MapString.get(recipes, recipeId), (function (recipe) {
                                          return React.createElement("div", {
                                                      key: recipeId,
                                                      onClick: (function (param) {
                                                          return RescriptReactRouter.push("/recipes/" + recipe.id);
                                                        })
                                                    }, recipe.title);
                                        }));
                          })), Belt_Option.isSome), (function (prim) {
                    return prim;
                  })));
}

var make = RecipeList;

export {
  make ,
  
}
/* react Not a pure module */
